### PR TITLE
Added PROCESS_ALL_ACCESS

### PR DESCRIPTION
**Pull request by elmoiv**
All possible access rights for a process object.
This will return max access that DACL allows. May solve problems with some processes

### CODE REVIEW

**Comment by vsantiago113** [comment]
Can you give me more information about your plan? The method you added you are not using it anywhere. Were you thinking about replacing the dw_desired_access on the Open method for yours to pass process_all_access instead of the 4 permissions I am passing there?

**Comment by elmoiv** [comment]
I created it as a new function as both have pros and cons.

`dw_desired_access` worked with some games where `process_all_access` didn't work and vice versa.
`process_all_access` worked with "**Ori and the blind forest**" game and "**Trepang 2**" where `dw_desired_access` didn't.

I mean you could add this as another option when the normal way of getting handle doesn't work properly.

**Comment by vsantiago113** [comment]
Awesome, now we have to add a parameter or something to be able to pick with what permissions we want the handle to have when opening the process. Thanks for contributing this, I appreciate it.

**Comment by elmoiv** [comment]
Can we re-implement it to work with x64 bit processes?

**Pull request merged**
